# Generated by Django 5.2.8 on 2026-04-17 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_delete_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
